hl.on('hyprland.start', function()
  hl.exec_cmd '/etc/profile.d/flatpak.sh'
  hl.exec_cmd 'dbus-update-activation-environment --systemd HYPRLAND_INSTANCE_SIGNATURE'
  hl.exec_cmd 'dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP'
  hl.exec_cmd 'dbus-update-activation-environment --systemd --all'
  hl.exec_cmd 'systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP'
  hl.exec_cmd 'systemctl --user start hyprpolkitagent'
  hl.exec_cmd '~/.config/hypr/scripts/xdg-desktop-portal.sh'
  hl.exec_cmd 'swaync'
  hl.exec_cmd 'nm-applet'
  hl.exec_cmd 'hyprpaper'
  hl.exec_cmd 'hypridle'
  hl.exec_cmd '~/.config/hypr/scripts/waybar.sh'
  hl.exec_cmd '~/.config/hypr/scripts/wallpaper.sh'
  hl.exec_cmd '~/.config/hypr/scripts/cleanup.sh'
  hl.exec_cmd 'wl-paste --watch cliphist store'
  hl.exec_cmd 'hyprctl setcursor Bibata-Modern-Ice 20'
  hl.exec_cmd 'gsettings set org.gnome.desktop.interface cursor-theme "Bibata-Modern-Ice"'
  hl.exec_cmd 'gsettings set org.gnome.desktop.interface cursor-size 20'
end)
