# windowrule = float on, match:class ^([Rr]ofi)$
# windowrule = center on, match:class ^([Rr]ofi)$
# windowrule = float on,match:class ^(pavucontrol)$
# windowrule = float on,match:class ^(vlc)$
# windowrule = float on,match:class ^(qt5ct)$
# windowrule = float on,match:class ^(qt6ct)$
# windowrule = float on,match:title ^(About Mozilla Firefox)$
# windowrule = float on,match:class ^(firefox)$,match:title ^(Picture-in-Picture)$
# windowrule = float on,match:class ^(firefox)$,match:title ^(Library)$
# windowrule = tile on,match:class ^(Chromium)$
# windowrule = tile on,match:class ^(Brave-browser)$
# windowrule = tile on,match:class ^(Microsoft-edge)$
# windowrule = tile on,match:class ^([Ss]team)$
# windowrule = float on,match:class ^(pavucontrol)$
# windowrule = float on,match:class ^(org.pulseaudio.pavucontrol)$
# windowrule = float on,match:class ^(blueman-manager)$
# windowrule = float on,match:class ^(nm-connection-editor)$
# windowrule = float on,match:class ^(nm-applet)$
# windowrule = float on,match:class ^(qalculate-gtk)$
# windowrule = float on,match:class ^(org.kde.dolphin)$,match:title ^(Progress Dialog — Dolphin)$
# windowrule = float on,match:class ^(org.kde.dolphin)$,match:title ^(Copying — Dolphin)$
# windowrule = float on,match:class ^(nwg-look)$
# windowrule = float on,match:class ^(org.kde.ark)$
# windowrule = float on,match:class ^(org.kde.polkit-kde-authentication-agent-1)$

# windowrule = float on,match:class (org.gnome.Calculator)
# windowrule = size 700 600,match:class (org.gnome.Calculator)
# windowrule = center on,match:class (org.gnome.Calculator)

# layerrule = blur,rofi
# layerrule = ignorezero,rofi
# layerrule = ignorealpha 0.5, swaync-control-center
# layerrule = ignorealpha 0.5, swaync-notification-window
# layerrule = blur, swaync-control-center
# layerrule = blur, swaync-notification-window
# layerrule = ignorealpha 0.5, gtk-layer-shell
# layerrule = blur, gtk-layer-shell
