#! /bin/sh

export _JAVA_AWT_WM_NONREPARENTING=1

sxhkd &
xrdb -merge ~/.config/xfiles/xresources
picom &
xrandr --output DP-4 --primary --mode 2560x1440 --rate 144 --left-of DP-0 &

bspc monitor DP-4 -d 1 2 3 4 5 6
bspc monitor DP-0 -d 7 8 9 0

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config normal_border_color "#1e1e1e"
bspc config active_border_color "#1e1e1e"
bspc config focused_border_color "#cc881a"
bspc config external_rules_command ~/.config/bspwm/external_rules

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
bspc rule -a Thunderbird desktop="^4" follow=on
bspc rule -a vlc desktop="^5" follow=off
bspc rule -a quassel desktop="^8" follow=on
bspc rule -a "TeamSpeak 3" desktop="^9" floating=on split_dir=up follow=off
bspc rule -a Steam desktop="^9" split_dir=right floating=on follow=off
bspc rule -a Lollypop desktop="^10" follow=off

# autostart programs
feh --bg-center --no-fehb ~/.local/share/wallpaper/current
${HOME}/.config/polybar/launch.sh
/etc/xdg/plasma-workspace/shutdown/10-agent-shutdown.sh
ghostty &
