local gh = function(repo)
  return ('https://github.com/%s.git'):format(repo)
end

return {
  gh 'MunifTanjim/nui.nvim',
  gh 'echasnovski/mini.icons',
  gh 'nvim-lua/plenary.nvim',
  { src = gh 'saghen/blink.cmp', version = vim.version.range '1' },
  gh 'rafamadriz/friendly-snippets',
  gh 'neovim/nvim-lspconfig',
  gh 'mason-org/mason.nvim',
  gh 'WhoIsSethDaniel/mason-tool-installer.nvim',
  gh 'folke/neoconf.nvim',
  gh 'nvim-treesitter/nvim-treesitter',
  gh 'nvim-treesitter/nvim-treesitter-textobjects',
  gh 'windwp/nvim-ts-autotag',
  gh 'folke/tokyonight.nvim',
  gh 'folke/snacks.nvim',
  gh 'folke/persistence.nvim',
  gh 'Spelis/project.nvim',
  { src = gh 'ThePrimeagen/harpoon', version = 'harpoon2' },
  gh 'stevearc/oil.nvim',
  gh 'ibhagwan/fzf-lua',
  gh 'folke/todo-comments.nvim',
  gh 'windwp/nvim-autopairs',
  gh 'nmac427/guess-indent.nvim',
  gh 'folke/ts-comments.nvim',
  gh 'MagicDuck/grug-far.nvim',
  gh 'folke/flash.nvim',
  { src = gh 'kylechui/nvim-surround', version = vim.version.range '*' },
  gh 'brenoprata10/nvim-highlight-colors',
  gh 'folke/lazydev.nvim',
  { src = gh 'akinsho/bufferline.nvim', version = vim.version.range '*' },
  gh 'nvim-lualine/lualine.nvim',
  gh 'folke/which-key.nvim',
  gh 'folke/noice.nvim',
  gh 'MeanderingProgrammer/render-markdown.nvim',
  gh 'iamcco/markdown-preview.nvim',
  gh 'stevearc/conform.nvim',
  gh 'mfussenegger/nvim-lint',
}
