#!/bin/sh
xrandr --output DisplayPort-2 --left-of HDMI-A-0
# 144 hz
xrandr --output DisplayPort-2 --mode 2560x1440 --rate 144

xrdb -merge -I$HOME ~/.Xresources
i3-msg restart
polybar-msg cmd restart
