return {
  'nvim-treesitter/nvim-treesitter',
  event = { 'BufReadPre', 'BufNewFile' },
  build = ':TSUpdate',
  dependencies = {
    'windwp/nvim-ts-autotag',
  },
  config = function()
    require('nvim-treesitter.configs').setup {
      auto_install = false,
      sync_install = false,
      highlight = { enable = true },
      indent = { enable = true },
      autotag = { enable = true },
      incremental_selection = {
        enable = true,
        keymaps = {
          init_selection = '<Enter>',
          node_incremental = '<Enter>',
          scope_incremental = false,
          node_decremental = '<BS>',
        },
      },
      ensure_installed = {
        'bash',
        'c',
        'cmake',
        'cpp',
        'css',
        'desktop',
        'devicetree',
        'diff',
        'dockerfile',
        'git_config',
        'git_rebase',
        'gitattributes',
        'gitcommit',
        'gitignore',
        'go',
        'gomod',
        'gosum',
        'gpg',
        'html',
        'hyprlang',
        'ini',
        'java',
        'javascript',
        'json',
        'jsonc',
        'jq',
        'lua',
        'markdown',
        'markdown_inline',
        'ninja',
        'passwd',
        'properties',
        'python',
        'query',
        'ssh_config',
        'tmux',
        'toml',
        'tsx',
        'typescript',
        'udev',
        'vim',
        'vimdoc',
        'xml',
        'yaml',
        'zig',
      },
    }
  end,
}
