[general]
import = [
	"~/.config/alacritty/themes/tokyonight_moon.toml"
]

[env]
TERM = "xterm-256color"

[terminal]
shell = "/usr/bin/zsh"

[window]
padding.x = 10
padding.y = 10
decorations = "None"
opacity = 0.9
blur = true

[font]
size = 14
normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font"
bold_italic.family = "JetBrainsMono Nerd Font"
